# 주로 사용하는 library import

In [1]:
import pandas as pd
import numpy as np

#실행3_1_1

In [2]:
x=np.array([1,2,3,4,5]) #직접입력
df1 = pd.DataFrame({'col1':x,
 'col2':x+2,
 'col3': ['a', 'b', 'C', 'd', 'e']})
print(df1)

   col1  col2 col3
0     1     3    a
1     2     4    b
2     3     5    C
3     4     6    d
4     5     7    e

#실행3_1_2

In [3]:
#내컴퓨터에서 직접 업로드
from google.colab import files
#파일 업로드
uploaded = files.upload() #colab에서는 target_dir 사용불가: 원래 uploaded = files.upload('경로') 입력함
#csv 파일 불러오기
df2 = pd.read_csv('t2.1_test.csv')
print(df2)
#파일선택 버튼이 생성되면, 버튼을 눌러 로컬 파일 선택하여 df2에 저장

KeyboardInterrupt:

#실행3_1_3

In [4]:
#Google Drive 연동 후 불러오기
from google.colab import drive
#구글 드라이브 마운트(연결)
drive.mount('/content/drive')
#드라이브에 저장된 파일 경로 지정
file_path = '/content/drive/MyDrive/Colab_ex_data/t2.1_test.csv'
#데이터프레임 만들기
df3 = pd.read_csv(file_path)
print(df3)

Mounted at /content/drive

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab_ex_data/t2.1_test.csv'

In [ ]:
###참고
#Colab 파일에 업로드후 불러오기, 파일에 드래그해서 놓기
#가장 간편하나 코랩 실행시마다 업로드해야하는 단점이 있음, 일정 시간 동안은 살아있음
df33 = pd.read_csv('t2.1_test_colab.csv')
print(df33)

#실행3_1_4

In [ ]:
#변수명이 없는 csv파일 경로 지정
file_path = '/content/drive/MyDrive/Colab_ex_data/t2.1_test2.csv'

# 데이터프레임 만들기
df4 = pd.read_csv(file_path,header=None) #header=None: 변수 명이 없다는 표시
print(df4)

#실행3_1_5

In [ ]:
#txt파일 경로 지정
file_path = '/content/drive/MyDrive/Colab_ex_data/t2.1_test.csv'
# 데이터프레임 만들기
df5 = pd.read_csv(file_path,delimiter='\t') #delimiter='구분자' 지정, \t':탭으로 구분된 파일
print(df5)

#실행3_1_6

In [ ]:
#csv로 저장하기
df3.to_csv('df3_csv.csv')
#txt로 저장하기
df3.to_csv('df3_txt.txt', sep='\t') #sep=separator(구분자)
#Colab 파일의 content 폴더에 생성, 다운로드하여 사용

#실행 3_1_7

In [5]:
#Scikit-learn 라이브러리의 내장데이터 불러오기
from sklearn import datasets

iris=datasets.load_iris() #load_내장데이터명, Bunch라는 클래스 객체 형식으로 생성
print(iris.data[:5]) #data: 독립변수배열, feature_names: 독립변수이름리스트
print(iris.data.shape)  #shape: 몇 행 몇 열인지 보여줌
print(iris.feature_names) #feature_names: 데이터의 열 이름(변수명) 리스트를 보여줌

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
(150, 4)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [ ]:
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names) #iris.data: 독립변수 데이터 배열
print(df_iris)
print(df_iris.info()) #데이터 변수 타입 및 결측제외 데이터수

In [ ]:
print(iris.target_names)  #종속변수 값의 라벨
print(iris.target)  #종속변수 값

#실행3_1_8

In [16]:
#Scikit-learn 라이브러리의 california_housing 데이터 import
from sklearn.datasets import fetch_california_housing  #fetch하는 모듈이 있음

#fetch 데이터 불러오기, 인터넷 연결 필수
housing = fetch_california_housing()
#fetch_데이터명, Bunch라는 클래스 객체 형식으로 생성

#DataFrame으로 변환
df_housing = pd.DataFrame(housing.data, columns=housing.feature_names)
#data: 독립변수 배열, feature_names: 독립변수 이름리스트

In [ ]:
#target(종속변수값) 추가
print(housing.target_names) #target_names는 종속변수 값의 라벨

In [ ]:
df_housing["MedHouseValue"] = housing.target #target은 종속변수 배열

print(df_housing.head())
print(df_housing.info()) #데이터 변수 타입 및 결측제외 데이터수

#연습3_1

In [17]:
import pandas as pd
#Google Drive 연동 후 불러오기
from google.colab import drive

#구글 드라이브 마운트(연결)
drive.mount('/content/drive')

#txt파일 경로 지정
file_path1 = '/content/drive/MyDrive/Colab_ex_data/titanic_passenger.csv'

#데이터프레임 만들기
df_titanic_p = pd.read_csv(file_path1)
print(df_titanic_p.head())

#txt파일 경로 지정
file_path2 = '/content/drive/MyDrive/Colab_ex_data/titanic_info.txt'

# 데이터프레임 만들기
df_titanic_i = pd.read_csv(file_path2,delimiter='\t')
print(df_titanic_i.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   ID sex   age  sibsp  parch who
0   1   m  22.0      1      0   m
1   2   f  38.0      1      0   w
2   3   f  26.0      0      0   w
3   4   f  35.0      1      0   w
4   5   m  35.0      0      0   m
   ID  survived  pclass     fare embarked  class deck  embark_town
0   2         1       1  71.2833        C      1    C    Cherbourg
1   4         1       1  53.1000        S      1    C  Southampton
2   7         0       1  51.8625        S      1    E  Southampton
3  12         1       1  26.5500        S      1    C  Southampton
4  24         1       1  35.5000        S      1    A  Southampton

In [18]:
import seaborn as sns #seaborn은 Bunch타입이 아니라 데이터 프레임 형태로 바로 생성됨(데이터프레임으로 만드는 작업을 거치지 않아도 됨)
df_titanic = sns.load_dataset('titanic')

print(df_titanic.head())

print(df_titanic.info())  #object: 범주형 변수

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None

#실행 3_2_1

In [6]:
b=np.arange(0,12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
df6=pd.DataFrame(b,columns=['X1','X2','X3'])
df6

   X1  X2  X3
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11

In [8]:
df6.loc[1,['X1','X3']]=np.nan #df.loc[행선택, 열선택]: 행번호/열이름 으로 데이터 선택, 지정한 자리에 NaN을 부여함
df6.loc[2, 'X2'] =np.nan #np.nan은 float 타입으로 저장
df6.loc[3, 'X2'] = np.nan
df6

    X1   X2    X3
0  0.0  1.0   2.0
1  NaN  4.0   NaN
2  6.0  NaN   8.0
3  9.0  NaN  11.0

In [9]:
#결측확인
import numpy as np
print(df6.isnull().sum()) #변수별 결측치 개수
print(df6.info()) #데이터 변수 타입 및 결측제외 데이터수

X1    1
X2    2
X3    1
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      3 non-null      float64
 1   X2      2 non-null      float64
 2   X3      3 non-null      float64
dtypes: float64(3)
memory usage: 228.0 bytes
None

In [10]:
#결측을 0으로 대체
df6_1=df6.fillna(0)  #fillna(): NaN을 0으로 대체
print(df6_1)

    X1   X2    X3
0  0.0  1.0   2.0
1  0.0  4.0   0.0
2  6.0  0.0   8.0
3  9.0  0.0  11.0

In [11]:
#결측을 99로 대체
df6_2=df6.fillna(99)
print(df6_2)

     X1    X2    X3
0   0.0   1.0   2.0
1  99.0   4.0  99.0
2   6.0  99.0   8.0
3   9.0  99.0  11.0

In [12]:
#결측을 앞의 값으로 대체
df6_3=df6.fillna(method='ffill')
print(df6_3)

    X1   X2    X3
0  0.0  1.0   2.0
1  0.0  4.0   2.0
2  6.0  4.0   8.0
3  9.0  4.0  11.0

/tmp/ipython-input-3004785790.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6_3=df6.fillna(method='ffill')

In [13]:
df6_3_limit=df6.fillna(method='ffill', limit=1) #limit= 옵션으로 대체하는 개수 제한 가능, 열별로 1개의 NaN만 대체
print(df6_3_limit)

    X1   X2    X3
0  0.0  1.0   2.0
1  0.0  4.0   2.0
2  6.0  4.0   8.0
3  9.0  NaN  11.0

/tmp/ipython-input-833526328.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6_3_limit=df6.fillna(method='ffill', limit=1) #limit= 옵션으로 대체하는 개수 제한 가능, 열별로 1개의 NaN만 대체

In [14]:
#결측을 뒤의 값으로 대체  #X2의 2는 뒷값도 NaN이라 그대로 NaN
df6_4=df6.fillna(method='bfill')
print(df6_4)

    X1   X2    X3
0  0.0  1.0   2.0
1  6.0  4.0   8.0
2  6.0  NaN   8.0
3  9.0  NaN  11.0

/tmp/ipython-input-355213417.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6_4=df6.fillna(method='bfill')

In [19]:
#결측을 변수별 평균으로 대체
df6_5=df6.fillna(df6.mean())
print(df6_5)

    X1   X2    X3
0  0.0  1.0   2.0
1  5.0  4.0   7.0
2  6.0  2.5   8.0
3  9.0  2.5  11.0

In [22]:
#결측을 모두 X1변수의 평균으로 대체
df6_6=df6.fillna(df6.mean()['X1'])
print(df6_6)

    X1   X2    X3
0  0.0  1.0   2.0
1  5.0  4.0   5.0
2  6.0  5.0   8.0
3  9.0  5.0  11.0

In [21]:
#결측인 데이터 삭제
df6_7=df6.dropna()
print(df6_7)

    X1   X2   X3
0  0.0  1.0  2.0

In [20]:
#특정 변수의 결측 데이터 삭제
df6_8=df6.dropna(subset=["X3"])
print(df6_8)

    X1   X2    X3
0  0.0  1.0   2.0
2  6.0  NaN   8.0
3  9.0  NaN  11.0

#실행 3_2_2. 데이터 정렬해보기

In [ ]:
df7 = pd.DataFrame({
 'name': ['KIM', 'LEE', 'Park', np.nan, 'Kang'],
 'age': [24, 32, 43, 24, np.nan],
 'height': [160, 170, 165, 173, 158]})
print(df7)

In [ ]:
#순위 변수의 생성
df7['rank_age']=df7['age'].rank(method='min', ascending=False,na_option='bottom')
 #metod='min':동점일경우 최솟값을 부여
 #ascending=False: 내림차순(나이 많은 순서대로), ascending=True가 디폴트
 #na_option='bottom': 결측은 후순위(선순위는 'top')
print(df7)

In [ ]:
df7['rank_age']=df7['age'].rank(method='min', ascending=False)
print(df7)

In [ ]:
#age 기준으로 오름차순 정렬
df7_1=df7.sort_values(by='age')
print(df7_1)

#age 기준으로 내림차순 정렬
df7_2=df7.sort_values(by='age', ascending=False)
print(df7_2)

In [ ]:
#두 변수 기준으로 내림차순 정렬
df7_4=df7.sort_values(by=['age', 'height'], ascending=False)
print(df7_4)

In [ ]:
#age 내림차순, height 오름차순 정렬
df7_5=df7.sort_values(by=['age', 'height'], ascending=[False, True]) #데이터프레임에 적용하는 함수는 거의 pandas에서 온 것임
print(df7_5)

#실행3_2_3. 다양한 데이터 유형의 결측 처리

In [ ]:
#결측을 변수별로 따로 지정
df7_4['name']=df7_4['name'].fillna('KKKKK') #고정값 KKKKK 로
df7_4['age'] = df7_4['age'].fillna(df7_4['age'].mean()) #평균으로
df7_4['height'] = df7_4['height'].fillna(method='ffill') #height는 앞의 값으로(ffill)
print(df7_4)

In [ ]:
#결측을 딕셔너리(dict) 형식으로 지정
fill_values = {'name': 'KKKKK', # 고정값 KKKKK 로
 'age': df7_5['age'].mean(), # 평균으로
 'height': df7_5['height'].max()} # 최대값으로

df7_6 = df7_5.fillna(fill_values) #딕셔너리 데이터를 이용해서 한번에 지정할 수 있음
print(df7_6)

In [ ]:
df7_6_1 = df7_5.fillna({'name': 'KKKKK', # 고정값 KKKKK 로
 'age': df7_5['age'].mean(), # 평균으로
 'height': df7_5['height'].max()}) # 최대값으로
print(df7_6_1)

#연습3_2

In [23]:
#결측치 확인
print(df_titanic_p.isnull().sum())  #변수별 결측치 개수
print(df_titanic_p.info())          #데이터 타입 및 결측제외 데이터수
print(df_titanic_i.isnull().sum())  #변수별 결측치 개수
print(df_titanic_i.info())          #데이터 타입 및 결측제외 데이터수

ID         0
sex        9
age      177
sibsp      0
parch      0
who        0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      891 non-null    int64
 1   sex     882 non-null    object
 2   age     714 non-null    float64
 3   sibsp   891 non-null    int64
 4   parch   891 non-null    int64
 5   who     891 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 41.9+ KB
None
ID               0
survived         0
pclass           0
fare             0
embarked         2
class            0
deck           688
embark_town      2
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   fare         891 non-null    float64
 4   embarked     889 non-null    object
 5   class        891 non-null    int64
 6   deck         203 non-null    object
 7   embark_town  889 non-null    object
dtypes: float64(1), int64(4), object(3)
memory usage: 55.8+ KB
None

In [24]:
#sex 변수의 결측은 삭제하고, age 결측은 평균값으로 대체
df_titanic_p=df_titanic_p.dropna(subset=['sex'])
df_titanic_p['age']=df_titanic_p['age'].fillna(df_titanic_p['age'].mean())

print(df_titanic_p.isnull().sum())  #변수별 결측치 개수
print(df_titanic_p.info())          #데이터 타입 밒 결측제외 데이터수

ID       0
sex      0
age      0
sibsp    0
parch    0
who      0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 882 entries, 0 to 890
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      882 non-null    int64
 1   sex     882 non-null    object
 2   age     882 non-null    float64
 3   sibsp   882 non-null    int64
 4   parch   882 non-null    int64
 5   who     882 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 48.2+ KB
None

In [26]:
#embark_town 변수의 결측은 'Unknown'으로 대체
df_titanic_i['embark_town']=df_titanic_i['embark_town'].fillna('Unknown')

print(df_titanic_i.isnull().sum())  #변수별 결측치 개수
print(df_titanic_i.info())          #데이터 타입 및 결측제외 데이터수

#rank_fare 생성
df_titanic_i['rank_fare']=df_titanic_i['fare'].rank(method='min',ascending=False,na_option='bottom')
dt_titanic_i=df_titanic_i.sort_values(by='rank_fare') #보기 편하라고 sort시킴
print(df_titanic_i.head())

ID               0
survived         0
pclass           0
fare             0
embarked         2
class            0
deck           688
embark_town      0
rank_fare        0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   fare         891 non-null    float64
 4   embarked     889 non-null    object
 5   class        891 non-null    int64
 6   deck         203 non-null    object
 7   embark_town  891 non-null    object
 8   rank_fare    891 non-null    float64
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB
None
   ID  survived  pclass     fare embarked  class deck  embark_town  rank_fare
0   2         1       1  71.2833        C      1    C    Cherbourg      103.0
1   4         1       1  53.1000        S      1    C  Southampton      142.0
2   7         0       1  51.8625        S      1    E  Southampton      157.0
3  12         1       1  26.5500        S      1    C  Southampton      270.0
4  24         1       1  35.5000        S      1    A  Southampton      195.0

#실행3_3_1. 변수 속성과 이름 바꿔보기

In [ ]:
#변수 속성 확인하기
print(df7_4.dtypes)  #object가 문자데이터 타입
print(df7_4.info())

In [ ]:
#height를 정수형으로 변환
df7_4['height'] = df7_4['height'].astype('float64') #Int64는 결측허용, Int는 결측허용안함
#age를 반올림후 정수형으로 변환
df7_4['age'] = df7_4['age'].round().astype('Int64')
#rank_age를 문자형으로 변환
df7_4['rank_age'] = df7_4['rank_age'].astype('str')

print(df7_4.dtypes)
df7_4

In [ ]:
#변수 이름 바꾸기
df7_6 = df7_4.rename(columns={'name': 'x1', 'age': 'x2', 'height': 'x3', 'rank_age': 'x4'})
df7_6

#실행3_3_2

In [ ]:
df8 = pd.DataFrame({'name': ['Kim', 'Lee', 'Park', 'Choi', 'Song', 'Moon'],
 'age': [23, 30, 29, 32, 41, 47],
 'english': [90, 80, 70, 40, 50, 60],
 'math': [82, 75, 95, 44, 68, 90]})

In [ ]:
#기본
df8['total1'] = df8['english'] + df8['math'] # 총점 변수 파생
df8['avg1'] = df8['total1'] / 2 # 평균 변수 파생

In [ ]:
#assign : 여러 열을 간단한 수식으로 파생할 때 적합
df8 = df8.assign(total2 = df8['english'] + df8['math'],
 avg2 = (df8['english'] + df8['math']) / 2)
print(df8)

#실행3_3_3. 변수에 조건 지정하여 새로운 그룹변수 파생

In [ ]:
#assign/pd.cut 사용
df8 = df8.assign(age_g1 = pd.cut(df8['age'],
 bins=[0, 20, 30, 40, 50], # 구간 경계 (]가 디폴트
 labels=['20대미만', '20대', '30대', '40대'], # 라벨
 right=False)) # 구간을 [) 로 바꿈

In [ ]:
#assign/np.select 사용
conditions = [df8['age'] >= 40,
 df8['age'] >= 30,
 df8['age'] >= 20]
choices = ['40대', '30대', '20대']
df8 = df8.assign(age_g2 = np.select(conditions, choices, default='기타')) #np.select(조건,출력, 조건이 없는 나머지)
print(df8)

#연습 3-3

In [ ]:
#fare 반올림 후 정수형으로 변환
df_titanic_i['fare'] = df_titanic_i['fare'].round().astype('Int64')

#변수 이름 바꾸기
df_titanic_i = df_titanic_i.rename(columns={'embarked': 'embarked_port'})

df_titanic_i

In [ ]:
#family_n 생성
df_titanic_p['family_n'] = df_titanic_p['sibsp'] + df_titanic_p['parch']
print(df_titanic_p.head())

#pclass_2 생성
#assign/np.select 사용
conditions=[df_titanic_i['pclass']==1,
            df_titanic_i['pclass']==2,
            df_titanic_i['pclass']==3]
choices=['First', 'Second', 'Third']
df_titanic_i=df_titanic_i.assign(pclass_2=np.select(conditions, choices, default='etc'))
print(df_titanic_i.head())

#3_4_1. 특정 열(변수)만 선택하기

In [ ]:
df8_1 = df8[['name', 'age', 'english', 'math', 'total1', 'avg1', 'age_g1']] #직접 지정
df8_1 = df8_1.rename(columns={'total1': 'total', 'avg1': 'avg', 'age_g1': 'age_g'}) #변수명 수정
print(df8_1)

In [ ]:
#열 인덱스로 선택
df8_2 = df8.iloc[:, [0,1,2,3,4,5]]  #[행, 열]
print(df8_2)

#연속된 변수 선택
df8_3 = df8.iloc[:, 0:5]  #0:5는 0부터 4번까지 지정됨
print(df8_3)

In [ ]:
#특정한 열만 삭제
df8_4 = df8.drop(columns=['total2', 'avg2', 'age_g2'])
print(df8_4)

#실행 3_4_2. 특정한 값을 가진 행(관측치)만 선택하기

In [ ]:
#조건을 지정하여 선택하기
df8_5 = df8_1[df8_1['math'] >= 70] #수학점수가 70이상인 학생만 선택
print(df8_5)
df8_6 = df8_1[(df8_1['name'] == 'Kim') | (df8_1['name'] == 'Lee')] #이름으로 선택
print(df8_6)
df8_7 = df8_1[df8_1['name'].isin(['Kim', 'Lee'])] #isin 함수로 더 간단히 선택
print(df8_7)

#실행 3_4_3. 데이터 세로 결합, 가로 결합

In [ ]:
#데이터 생성하기
df_c1 = pd.DataFrame({'name': ['Kim', 'Lee', 'Park'], 'english': [90, 80, 70], 'math': [82, 75, 95]})
df_c2 = pd.DataFrame({'name': [ 'Choi', 'Song', 'Moon'], 'english': [ 40, 50, 60], 'math': [44, 68, 90]})
df_c3 = pd.DataFrame({'name': [ 'Jeong', 'Min', 'Oh'], 'english': [ 80, 50, 30], 'math': [54, 64, 88]})
df_teacher = pd.DataFrame({'class': ['c1', 'c2', 'c4'], 'teacher': ['Prof. Park', 'Prof. Lee', 'Prof. Choi']})

# 각각에 class 변수 부여
df_c1['class'] = 'c1'
df_c2['class'] = 'c2'
df_c3['class'] = 'c3'

print(df_c1)
print(df_c2)
print(df_c3)
print(df_teacher)

In [ ]:
# 세로로 합치기
df_all = pd.concat([df_c1, df_c2, df_c3], ignore_index=True)
#ignore_index=True: 인덱스를 무시하고 0,1,2,… 새로 생성
#ignore_index=False (기본값): 원래 DataFrame 인덱스를 유지하므로 중복
print(df_all)

In [ ]:
df_all = pd.concat([df_c1, df_c2, df_c3])
#ignore_index=True: 인덱스를 무시하고 0,1,2,… 새로 생성
#ignore_index=False (기본값): 원래 DataFrame 인덱스를 유지하므로 중복
print(df_all)

In [ ]:
#병합하기 (class 기준)
df_merge_i = pd.merge(df_all, df_teacher, on='class', how='inner')
print(df_merge_i)
df_merge_l = pd.merge(df_all, df_teacher, on='class', how='left')
print(df_merge_l)
df_merge_r = pd.merge(df_all, df_teacher, on='class', how='right')
print(df_merge_r)
df_merge_o = pd.merge(df_all, df_teacher, on='class', how='outer')
print(df_merge_o)

#연습3_4

In [ ]:
#inner 병합하기
df_titanic_m=pd.merge( df_titanic_p, df_titanic_i, on='ID', how='inner')
df_titanic_m

In [ ]:
df_titanic_m = df_titanic_m.drop(columns=['deck'])
df_titanic_m

In [ ]:
df_titanic_m_s0=df_titanic_m[df_titanic_m['survived'] == 0]
df_titanic_m_s1=df_titanic_m[df_titanic_m['survived'] == 1]
print(len(df_titanic_m_s0))
print(len(df_titanic_m_s1))

df_titanic_m_s01=pd.concat([df_titanic_m_s0,df_titanic_m_s1], ignore_index=True)
print(len(df_titanic_m_s01))