###실행2_1_1

In [ ]:
'A'
type('A')
type(1)  #마지막값만 나옴, 다 출력하고 싶으면 각각에 print 쓰기

int

In [ ]:
print('A')
print(type('A'))
print(type(1))
print(type(2.5))
print(type(True))

A
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

In [ ]:
#정수(int)
a = 10
print(a, type(a)) # 10 <class ‘int’>

#실수(float)
b = 3.14
print(b, type(b)) # 3.14 <class ‘float’>

#문자(str)
c = "Hello"
print(c, type(c)) # Hello <class ‘str’>

10 <class 'int'>
3.14 <class 'float'>
Hello <class 'str'>

In [ ]:
#부울(bool)
d = True
print(d, type(d)) # True <class ‘bool’>

True <class 'bool'>

In [ ]:
#리스트(list)
e = [1, 2, 3]
print(e, type(e))

#튜플(tuple)
f = (1, 2, 3) #값을 바꿀 수 없음
print(f, type(f))

[1, 2, 3] <class 'list'>
(1, 2, 3) <class 'tuple'>

In [ ]:
#리스트 형식과 튜플 형식의 차이는 값 수정이 가능한지 여부의 차이
my_list = [1, 2, 3]
my_list[0] = 100 #리스트의 첫 번째 데이터를 100으로 수정
print(my_list)

[100, 2, 3]

In [ ]:
my_tuple = (1, 2, 3)
my_tuple[0] = 100 #오류, 수정 못함

TypeError: 'tuple' object does not support item assignment

In [ ]:
#범위
g = range(1,10) #1부터 9까지
print(list(g)) #범위 내 정수

#딕셔너리(dict)
h = {"이름": "홍길동", "나이": 20}
print(h, type(h))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
{'이름': '홍길동', '나이': 20} <class 'dict'>

###실행2_2_1

In [ ]:
print( (2**3+1)/2 )
print( 1>2 )
print( 2<=3 )
print( 2==3 )
print( 2!=3 )
print( 3%2 )
print( 3//2 )
print( (2>3) & (4<5) )
print( (2>3) | (4<5) )

4.5
False
True
False
True
1
1
False
True

###실행 2_2_2

In [ ]:
abs(2-3)

1

In [ ]:
import math
math.sqrt(2)  #math라는 라이브러리 안에 있는 sqrt를 씀

1.4142135623730951

In [ ]:
import numpy as np
np.sqrt(2) #numpy라는 라이브러리 안에 있는 sqrt를 씀

np.float64(1.4142135623730951)

In [ ]:
np.sqrt(-3)

/tmp/ipython-input-1688310282.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-3)

np.float64(nan)

In [ ]:
math.factorial(3)

6

  ###실행 2_2_3

In [ ]:
import math

In [ ]:
a= math.ceil(5.76543) #올림
print(a)

b= math.floor(5.76543) #내림
print(b)

c= math.trunc(5.76543) #버림
print(c)


d=round(5.76543, 2) #반올림, 소수점이하 2 자리까지 표시
print(d)

6
5
5
5.77

In [ ]:
e= math.ceil(-5.76543)
print(e)

f= math.floor(-5.76543)
print(f)

g= math.trunc(-5.76543)
print(g)

h= round(-5.76543,2)
print(h)

-5
-6
-5
-5.77

###실행 2_2_4

In [ ]:
#함수 만들기
def ex_func(data): #ex_func: 함수 이름(숫자로 시작X), data: 인수
  return((data+2)*4) #Indent, 코랩에서 작성 시 들여쓰기 자동 반영, 윗즐에 속하는 명령임
ex_func(3)

20

In [ ]:
ex_func(3)+ex_func(4)

44

###실행 2_2_5

#클래스 만들기

In [ ]:
class Rectangle: #class 이름을 지정함
  def __init__(self,width,height): #self는 Rectangle에서 만드는 자기 자신(객체) #괄호 안은 인수
     self.width=width #속성(변수)
     self.height=height
  def area(self): #메서드(함수)
    return (self.width*self.height)

In [ ]:
# Rectangle은 변수도 지정되고, 함수도 지정됨
r = Rectangle(3, 4) #width=3, height=4

print(r.width)

3

In [ ]:
print(r.height)

4

In [ ]:
print(r.area()) #실제 실행 Rectangle.area(r), Ractangle 아래에 area 함수가 있음

12

###연습 2_1

In [ ]:
def g_func(a,b):
  c=a+b
  d=a-b
  e=a*b
  return(c,d,e)
g_func(3,4)

(7, -1, 12)

In [ ]:
class Rectangle2:
  def __init__(self,width,height): #생성자
    self.width=width #속성(변수)
    self.height=height
  def area(self):  #매서드(함수)
    return self.width*self.height
  def perimeter(self):  #매서드(함수)
    return self.width*2+self.height*2

q=Rectangle2(5,6)
print(q.width)
print(q.height)
print(q.area())
print(q.perimeter())

5
6
30
22

###실행2_3_1

In [ ]:
#데이터 벡터 만들기
import numpy as np
score_A = np.array([96, 80, 76, 96, 88, 75, 78, 89, 92, 70])
score_B = np.array([67, 83, 96, 90, 85, 75, 82, 89, 92, 75])
print(score_A)
print(score_B)

[96 80 76 96 88 75 78 89 92 70]
[67 83 96 90 85 75 82 89 92 75]

In [ ]:
#벡터 하나로 합치기
score_hstack = np.hstack([score_A, score_B]) #1행으로
print(score_hstack)
score_vstack = np.vstack([score_A, score_B]) #2행으로
print(score_vstack)
score_colstack = np.column_stack([score_A, score_B]) #벡터를 열방향으로 바꾸어 2 열로
print(score_colstack)

[96 80 76 96 88 75 78 89 92 70 67 83 96 90 85 75 82 89 92 75]
[[96 80 76 96 88 75 78 89 92 70]
 [67 83 96 90 85 75 82 89 92 75]]
[[96 67]
 [80 83]
 [76 96]
 [96 90]
 [88 85]
 [75 75]
 [78 82]
 [89 89]
 [92 92]
 [70 75]]

###실행2_3_2

In [ ]:
#이전에는 scipy의 sum, mean, var함수를 사용하기도 했으나 최신 버젼에서는 np만 쓰도록 정리됨
print(np.sum(score_A))
print(len(score_A)) #len(length) 기본이니까 np.를 붙이지 않음
print(np.mean(score_A))

840
10
84.0

In [ ]:
print(np.var(score_A))
print(np.var(score_A, ddof=0)) #모분산 : 편차제곱을 n 으로 나누기
print(np.var(score_A, ddof=1)) #표본분산 : 편차제곱을 n-1 로 나누기

78.6
78.6
87.33333333333333

In [ ]:
print(np.std(score_A))
print(np.std(score_A, ddof=0)) #모표준편차
print(np.std(score_A, ddof=1)) #표본표준편차

8.8656641037206
8.8656641037206
9.345230512584124

In [ ]:
print(np.amax(score_A))
print(np.amin(score_A))
print(np.median(score_A))

96
70
84.0

In [ ]:
print(np.percentile(score_A, 0))
print(np.percentile(score_A, 25)) #제1사분위수
print(np.percentile(score_A, 50)) #제2사분위수(중위수)
print(np.percentile(score_A, 75)) #제3사분위수
print(np.percentile(score_A, 100)) #제4사분위수

70.0
76.5
84.0
91.25
96.0

In [ ]:
from scipy import stats
summary = stats.describe(score_A) #stats라는 모듈 안의 describe 함수를 사용함
print(summary)

DescribeResult(nobs=np.int64(10), minmax=(np.int64(70), np.int64(96)), mean=np.float64(84.0), variance=np.float64(87.33333333333333), skewness=np.float64(-0.015498509592192651), kurtosis=np.float64(-1.4287046209428353))

###실행2_3_3

In [ ]:
print(score_A)

[96 80 76 96 88 75 78 89 92 70]

In [ ]:
print(score_A[0]) #첫번째 인덱스는 0부터 시작
print(score_A[1])
print(score_A[2])
print(score_A[8])
print(score_A[9])

96
80
76
92
70

In [ ]:
print(score_A[10]) #에러

IndexError: index 10 is out of bounds for axis 0 with size 10

In [ ]:
print(score_A[-1]) #뒤에서부터 세는 인덱스는 -1부터 시작
print(score_A[-2])
print(score_A[-9])
print(score_A[-10])

70
92
80
96

In [ ]:
print(score_A[1:4]) #인덱스 1,2,3 출력
print(score_A[7: ]) #인덱스가 7이상인 것부터 끝까지
print(score_A[ :7]) #처음부터 인덱스가 7인 것까지

###실행2_3_4

In [ ]:
import pandas as pd
#이름은 대소문자 구분
df=pd.DataFrame ({'grp_col_1': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
'grp_co1_2': [3,3,3,3,3,3,3,3,3,3],
'val_1': np.arange(10)}) #끝 지점인 10은 포함하지 않음
#arange는 일정한 간격의 숫자배열생성 함수
#np.arange(시작, 끝, 간격) 으로 지정, 시작과 간격은 생략 가능
df

  grp_col_1  grp_co1_2  val_1
0         a          3      0
1         b          3      1
2         c          3      2
3         d          3      3
4         e          3      4
5         f          3      5
6         g          3      6
7         h          3      7
8         i          3      8
9         j          3      9

In [ ]:
print(df)

  grp_col_1  grp_co1_2  val_1
0         a          3      0
1         b          3      1
2         c          3      2
3         d          3      3
4         e          3      4
5         f          3      5
6         g          3      6
7         h          3      7
8         i          3      8
9         j          3      9

In [ ]:
df.mean(numeric_only=True)
#판다스에서 제공하는 mean임
#데이터 프레임 내 숫자 변수의 평균 출력
#이전에는 df.mean() 로 실행 가능했으나 현재는 numeric_only=True 옵션 필수

grp_co1_2    3.0
val_1        4.5
dtype: float64

In [ ]:
df.mean(axis=0, numeric_only=True) #열 평균

In [ ]:
df.mean(axis=1, numeric_only=True) #행 평균

##연습 2_2

In [ ]:
k_score=np.array([93,76,87,92,98,75,82,92])
print('평균=',np.mean(k_score))
print('표본분산=',np.var(k_score, ddof=1))
print('표본편차=',np.std(k_score,ddof=1))
print('최대=',np.amax(k_score))
print('최소=',np.amin(k_score))
print('최소=',np.percentile(k_score,0)) #최소
print(np.percentile(k_score,25))
print(np.percentile(k_score,50))
print(np.percentile(k_score,75))
print(np.percentile(k_score,100))

평균= 86.875
표본분산= 70.98214285714286
표본편차= 8.425090080061036
최대= 98
최소= 75
최소= 75.0
80.5
89.5
92.25
98.0

In [ ]:
k_score[0]+k_score[1]+k_score[-1]

np.int64(261)

In [ ]:
df=pd.DataFrame({'Name':['kim','lee','park','oh','yang','min','jung','moon'], 'Korean':[93,76,87,92,98,75,82,92], 'English': [90,94,88,75,79,87,88,90]})
df

   Name  Korean  English
0   kim      93       90
1   lee      76       94
2  park      87       88
3    oh      92       75
4  yang      98       79
5   min      75       87
6  jung      82       88
7  moon      92       90

In [ ]:
df.mean(axis=0,numeric_only=True)

Korean     86.875
English    86.375
dtype: float64

In [ ]:
df.mean(axis=1,numeric_only=True)

0    91.5
1    85.0
2    87.5
3    83.5
4    88.5
5    81.0
6    85.0
7    91.0
dtype: float64

## 실행2_4_1

In [ ]:
#1,2,3,4 생성하기
for i in range(1,5):
 print(i) #Indent 들여쓰기

##실행2_4_2

In [ ]:
total = 0
for i in range(1, 11):
 total += i # total += i => total= total +i
 #print(total): 실행할 때마다 출력하고 싶으면 여기에 쓰기
total

In [ ]:
total = 0
for i in range(1, 11):
 total += i # total += i => total= total +i
 print(total) #실행할 때마다 출력됨

In [ ]:
total = 0
for i in range(1, 11):
 total += i # total += i => total= total +i
 print(i, ',', total)

##실행2_4_3

In [ ]:
# 100부터 200까지 합 구하기
start =100
end=200
isum=0
for i in range(start, end+1):
 isum = isum+i
print(isum) #unindent

##실행2_4_4

In [ ]:
import numpy as np
transport= np.array(["bus", "subway", "car", "bike"])
for vehicle in range(0,4):
 print(transport[vehicle])

##실행2_4_5

In [ ]:
for i in range(1,3):
 for j in range(1,4):
   print("곱셈식 ", f"{i}*{j}={i*j}") # f"..." : 문자열 안에 중괄호 { }안의 값을 넣어줌

##실행2_4_6

In [ ]:
for i in range(5):
 if i == 2:
   continue #조건에 해당하면 반복문의 현재 반복을 건너뛰고 다음 반복으로 넘어감
 print(i)
#i == 2일 때 continue가 실행되면서, print(i)는 건너뛰고 바로 다음 반복(i=3) 으로 넘어감

##실행2_4_7

In [ ]:
e=50
while e>1:
 e=e/3
 print(e)

##실행2_4_8

In [ ]:
data=3
if data<2:
 print("It is less than 2")
else:
 print(data, "is equal or greater than 2")

##실행2_4_9

In [ ]:
x=15
if (x < 10):
 print("One digit number")
elif x < 100: #들여쓰기 주의
 print("Two digit number")
else:
 print("More than two digit number")

##연습２_３

In [ ]:
for i in range(1, 21):
    # i를 2로 나눈 나머지가 0, 즉 i가 짝수이면
    if i % 2 == 0:
        # 현재 반복을 건너뛰고 다음 반복으로 넘어갑니다.
        continue
    # 짝수가 아니면 (홀수이면) 값을 출력합니다.
    print(i)

In [1]:
total_sum = 0
for i in range(1, 21):
    if i % 2 != 0:
        total_sum = total_sum + i
print(total_sum)

100

In [2]:
total = 0 # 합계를 저장할 변수를 초기화합니다.

for i in range(1, 21):
    # i가 짝수(i를 2로 나눈 나머지가 0)이면 건너뜁니다.
    if i % 2 == 0:
        continue

    # i가 홀수이면 total에 더합니다.
    total += i

print(f"1부터 20까지의 홀수의 합: {total}")

1부터 20까지의 홀수의 합: 100